baseURL = "https://osqa-ask.wireshark.org/"
languageCode = "en-us"
title = "Wireshark Q&A"
staticDir = [
    "static",
]
relativeURLs = true

# Pass raw HTML
# https://gohugo.io/news/0.60.0-relnotes/
[markup.goldmark.renderer]
unsafe = true