baseURL = "/"
languageCode = "en-us"
title = "Wireshark Q&A"
staticDir = [
    "static",
]
relativeURLs = true

# Matches OSQA's default.
paginate = 30

# Pass raw HTML.
# https://gohugo.io/news/0.60.0-relnotes/
[markup.goldmark.renderer]
unsafe = true
